config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    member do
      get :results
    end
  end

  root to: "questions#homepage"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_one :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  def homepage

  end
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
  end

  def results
    score_from_user = params[:score].to_i

    # look for the question
    # check its answer
    # if answer.score == score_from_user
    @question = Question.find(params[:id])
    @correct = @question.answer.score == score_from_user
    @next_question = Question.where("id > ?", @question.id).order(id: :asc).first
  end
  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :right_answer, :wrong_answer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerQuiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :right_answer %><br>
    <%= f.text_field :right_answer %>
  </div>
  <div class="field">
    <%= f.label :wrong_answer %><br>
    <%= f.text_field :wrong_answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/homepage.html.erb
  <div class="banana"></div>

  <div class="logo">

  <%= image_tag("logo.png", size: "100x115", id: "monkey")%>

  </div>

  <div class="buttonplay">
    <%= link_to "PLAY", questions_path, id: "playbutton" %>

  </div>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>


<% @questions.each do |question| %>
<p><%= link_to question.title, question_path( question.id ) %></p>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/results.html.erb
<div class="text">
<h1>results</h1>
</div>


<% if @correct %>
<div class="text">
  <h2>That's Correct!</h2>
  </div>
  <style>
body {background-color: green !important;}
  </style>
  <div style="background-color:green;", size="550x550", class="picture">

  <%= image_tag("smile", size: "500x350", color: "green")%>
  </div>
<% else %>

<style>
body {background-color: red !important;}
</style>

<div class="text">
  <h2>That's not right!</h2>
</div>
  <div style="background-color:red;", size="550x550">
  <%= image_tag("sad", size: "500x350", color: "red") %>
  </div>
<% end %>

<% if @next_question %>
  <%= link_to 'Next question', @next_question %>
<% else %>
  <%= link_to 'Done', questions_path %>
<% end %>

app/views/questions/show.html.erb
<p>
  <strong>Questions</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.content %>
</p>


<div class="buttons">
<%= link_to "True", results_question_path(@question, score: 1), id:"true", class:"shadow" %>
</div>

<div class="buttons">
<%= link_to "False", results_question_path(@question, score: 0), id:"false", class:"shadow" %>
</div>
<div class="buttons">
<%= link_to 'Back', questions_path, id:"buttonback", class:"shadow" %>
</div>